music/urls.py
from django.urls import path
from . import views
app_name='music'

urlpatterns=[
    path('',views.IndexView.as_view(),name='home'),
    path('<pk>/', views.DetailsView.as_view(), name='details'),
    path('album/add/',views.AlbumCreate.as_view(),name='album-add'),
    path('album/<pk>/',views.AlbumUpdate.as_view() ,name='album-update'),
    path('album/<pk>/delete/',views.AlbumDelete.as_view(),name='album-delete'),
   # path('<int:album_id>/favorite/',views.favorite,name='favorite'),
]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/',include('music.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse
class Album(models.Model):
    artist=models.CharField(max_length=250)
    album_title=models.CharField(max_length=500)
    genre=models.CharField(max_length=100)
    album_logo=models.FileField()

    def get_absolute_url(self):
        return reverse('music:details',kwargs={'pk':self.pk})


class Song(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=250)
    is_favorite=models.BooleanField(default=False)



music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=['username','email','password']

music/views.py
'''from django.shortcuts import render,get_object_or_404
from .models import Album,Song
def home(request):
    albums=Album.objects.all()
    context={'albums':albums}
    return render(request,'music/home.html',context)'''

'''def details(request,album_id):
    return HttpResponse("<h1>This album id is "+str(album_id)+ "</h1>")'''

'''def details(request,album_id):
   albums=get_object_or_404(Album,pk=album_id)
   context={'albums':albums}
   return render(request,'music/details.html',context)'''

'''def favorite(request,album_id):
    album=get_object_or_404(Album,pk=album_id)
    try:
        selected_song=album.song_set.get(pk=request.POST['song'])
    except (KeyError,Song.DoesNotExist):
        return render(request,'music/details.html',{
    'album':album,
    'error_message':"You did not select a valid song",
    })
    else:
        selected_song.is_favorite=True
        selected_song.save()
        return render(request,'music/details.html',{'album':album})'''

from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.views.generic import View
from .forms import UserForm
from .models import Album

class IndexView(generic.ListView):
    template_name='music/home.html'

    def get_queryset(self):
        return Album.objects.all()

class DetailsView(generic.DetailView):
    model=Album
    template_name='music/details.html'

class AlbumCreate(CreateView):
    model=Album
    fields=['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
    model=Album
    fields=['artist','album_title','genre','album_logo']

class AlbumDelete(DeleteView):
    model=Album
    success_url = reverse_lazy('music:home')



music/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
<link rel="stylesheet" href="{% static 'music/css/style.css' %}">
<link rel="stylesheet" href="{% static 'music/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  {% block head %}
  <title>Base</title>
  {% endblock %}
</head>
<body class="body">
    {% block navbar %}
   <div class="container">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'music:home' %}">Vibers</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="{%  url 'music:home' %}">
                               <span class="fa fa-music" aria-hidden="true" area-hidden="true"></span>&nbsp; Albums
                            </a>
                        </li>
                        <li class="">
                            <a href="{%  url 'music:home' %}">
                                <span class="fa fa-youtube-play" aria-hidden="true" area-hidden="true"></span>&nbsp; Songs
                            </a>
                        </li>
                       <form action="#" class="navbar-form navbar-left" role="search" method="get">
                           <div class="form-group">
                               <input type="text" class="form-control" name="q" value="">
                           </div>
                           <button type="button" class="btn btn-default">Search</button>
                       </form>
                       <ul class="nav navbar-nav navbar-right">
                           <li>
                               <a href="{% url 'music:album-add' %}">
                                   <span class="fa fa-plus" aria-hidden="true"></span>&nbsp;Add Album
                               </a>
                           </li>
                       </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#">
                                <span class="class="fa fa-sign-out" aria-hidden="true""></span>&nbsp;LogOut
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
   </div>
    {% endblock %}
    {% block body %}   
    <h1>Base</h1>
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

music/templates/music/album_form.html
{% extends 'base.html' %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <!---<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0-beta.2/solar/bootstrap.min.css">-->
    {% block head %}
    <title>AlbumDetails</title>
    {% endblock %}
</head>

<body>
    {% block body %}
    <div class="container">
        <div class="row">
            <div class="col col-sm-12 col-md-6">
                <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %} 
                    {% include 'music/form_template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}
</body>

</html>

music/templates/music/details.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
         {% load static %}
        {% block head %}
            <title>details</title>
        {% endblock %}
</head>
<body>
     {% block body %}
  <div class="container">
       <!--   This is <u><em style="color:orange">{{albums.album_title}} </em></u> and the id of this album is <u><em style="color:orange">{{albums.id}}</em></u>-->
    <table class="table table-bordered table-hover">
           <thead>
               <tr>
                   <th>Album_id</th>
                   <th>Song_Name</th>
                   <th>FileType</th>         
               </tr>
           </thead>
           {% for song in object_list.song_set.all %}
           <tbody>
               <tr>
                   <td>{{albums.id}}</td>
                   <td>{{song.song_title}}</td>                   
                   <td>{{song.file_type}}</td>
               </tr>
           </tbody>
             {% endfor %}
       </table>
      </div>
     {% endblock %}
</body>
</html>

music/templates/music/form_template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-2">{{field.label_tag}}</label>
    <div class="col-sm-10">{{field}}</div>
</div>
{% endfor %}

music/templates/music/home.html
{% extends 'base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!---<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0-beta.2/solar/bootstrap.min.css">-->
  {% block head %}
    <title>Home</title>
  {% endblock %}
</head>
<body>
 {% block body %}
<div class="container">
    <h2>Welcome to home page</h2>
    {% if object_list %}
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Artist:</th>
                <th>Album_Title</th>
                <th>Gener</th>
                <th>AlbumLogo</th>
                <th>DeteleAlbum</th>
            </tr>
        </thead>
        <tbody>
            {% for list in object_list %}
            <tr>
                <td>{{list.artist}}</td>
                <!--<td><a href="/music/{{list.id}}/">{{list.album_title}}</a></td>-->
                <td>
                    <a href="{% url 'music:details' list.id %}">{{list.album_title}}</a>
                </td>
                <td>{{list.genre}}</td>
                <td>
                    <img src="{{list.album_logo.url}}" alt="Not Show">
                </td>
                <td>
                   <div>
                       <span>
                            <form action="{% url 'music:album-delete' list.id %}" method="post" style="display:inline-block;" class="deleteForm">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{list.id}}"/>
                                <button type="submit" class="btn btn-default btn-sm" id="btn">
                                <span class="fa fa-trash-o" aria-hidden="true" style="font-size:2em;"></span>
                                </button>
                            </form>
                           <span>
                            <form action="{% url 'music:album-update' list.id %}" class="form-horizontal" method="post" enctype="multipart/form-data" style="display:inline-block;" >
                                {% csrf_token %}
                                {% include 'music/form_template.html' %}
                                <input type="hidden" name="album_id" value="{{list.id}}"/>
                                <button type="submit" class="btn btn-default btn-sm" id="pencil" value="Update">
                                    <span class="fa fa-pencil" aria-hidden="true" style="font-size:2em;"></span>
                                </button>
                          </form>
                           </span>
                       </span>
                   </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
 {% endblock %}
</body>
</html>